debiasing_method: cdisco

experiment_dir: test_opt_${predictor.encoder_type}_method_${predictor.method}_${predictor.optimizer_cfg.name}/lr_start_${predictor.optimizer_cfg.lr}_lr_end_${predictor.optimizer_cfg.lr_end}/bw_${predictor.bw}/cdcor_lambda_${predictor.cdcor_lambda}/warmup_${predictor.warmup_ratio}/seed_${seed}

hydra:
  sweeper:
    params:
      +seed: 42
      +predictor.bw: 0.1
      +predictor.cdcor_lambda: 10.0
      +predictor.warmup_ratio: 0.2
      +predictor.method: sdisco