data:
  name: mnli
  datamodule:
    _target_: ICML.data.mnli.mnli_dataset.MNLIDataModule
    csv_dir: ${dataset_path}/MNLI/processed_splits
    tensor_dir: ${dataset_path}/MNLI/processed_features
    num_workers: 8
    batch_size: 512

callbacks:
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: 'epoch'

predictor:
  encoder_type: tinybert
  pred_head: non-linear
  target: label_cat
  protected_attributes: [b]
  resnet_cfg:
    n_outputs: 3
  optimizer_cfg:
    name: adamw
    lr_end: 1e-08
    weight_decay: 0.01

logger:
  wandb:
    _target_: pytorch_lightning.loggers.WandbLogger
    project: "DISCO mnli sdisco fixed"
    name: "${debiasing_method}/${data.name}/${experiment_dir}"
    offline: False

trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: 1
  max_epochs: 20
  enable_progress_bar: True
  detect_anomaly: False
  log_every_n_steps: 1
  enable_checkpointing: true

hydra:
  job:
    chdir: True
  sweep:
    dir: results/${debiasing_method}/${data.name}/
    subdir: ${experiment_dir}/
  sweeper:
    params:
      +predictor.optimizer_cfg.lr: 0.00002
